### ISSUE TITLE
Identifier Problem

### ISSUE THREAD

**Issue by TehZombiJesus** [JaredScar/DiscordAcePerms#1]
Hey,

Tried the resource but didn't work.. when I checked the code in server.lua.

I noticed that your plugin uses Steam Identifier so I assume you might not know that es_extended doesn't use that anymore but License Identifier.

**add_principal identifier.license:5dd957d37dd59ac5256b99a291f674b7f916d3b3 group.admin**

**Comment by JaredScar** [comment]
Changed it to use discord identifiers now
