### ISSUE TITLE
Tutorial Request

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [JaredScar/DiscordAcePerms#11]
Is there a tutorial on how to actually add this into a script so the script can be whitelisted?

There is a script that I'm trying to add the ability for someone to use Discord Ace Perms with based on the roles in order to be able to activate the keybind command. But I'm having no luck. The script already comes with support for steam hex and such things but not ace perms. Thank you.

```
-- Standalone / Other
else
  Citizen.CreateThread(function()
    TriggerServerEvent(GetCurrentResourceName()..":CheckAccess")
  end)
end

hasAccess = false
RegisterNetEvent(GetCurrentResourceName()..":CheckAccess", function(bool)
  hasAccess = bool
end)
```

I dont think the guy who made the script knows how to do it. He set it up to allow esx and qbcore but for standalone he just put this... and said "its easy to setup" lol

**Comment by JaredScar** [comment]
I don't think this is a proper issue. This is moreso a request and this script is just for ACE permissions. Use FiveM's ACE permissions. No need to hook into this script.
