### ISSUE TITLE
Discord ace perms Deferring Connection

### ISSUE THREAD

**Issue by Baccalmog2** [JaredScar/DiscordAcePerms#13]
Hello, I just got discord ace perms but its stuck on Deferring Connection when i try to load in, I changed everything for like discord invites and followed a tutorial to install it but its not working please help.

**Comment by NickReagan** [comment]
@Baccalmog2 

Can you paste your config, with the discord and website links **removed**? There is an "Add Code" button in the text box just click that when pasting.
