### ISSUE TITLE
Code Issues

### ISSUE THREAD

**Issue by itscflat** [JaredScar/DiscordAcePerms#17]
Alright, so earlier today, I was going through the Badger Plugins I have to make sure they're alright before I move on, and yeah I fixed a couple, but here is where i'm stuck. I am told that at line 9 the bracket was not finished, even though at line 20 it's clearly finished, and I tried moving it around, restarting the code, changing the names to the role id's, even tried using a different bracket. Still no luck. Honestly any recommendations or help would be appreciated.

(https://github.com/JaredScar/DiscordAcePerms/assets/105817668/4413a722-4b67-4ead-8ca7-86e8277e73a5)

(https://github.com/JaredScar/DiscordAcePerms/assets/105817668/6e717a56-610f-4ac3-bcb9-8f8982088766)

**Comment by NickReagan** [comment]
You are missing commas on lines 16-18.

**Comment by itscflat** [comment]
> You are missing commas on lines 16-18.

Thanks for the help, it worked! It's understandable how easy it is to miss such a small character lol.
